use_frameworks!
platform :ios, '9.3'

target 'Drawer_Example' do
  pod 'Drawer', :path => '../'

  target 'Drawer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
